import type { Club } from "./features/clubs/dtos";

export const recommendedClubs: Club[] = [
  {
    id: "1",
    nome: "Clube Fantasia Viva",
    descricao:
      "Exploramos mundos mágicos, jornadas épicas e universos fantásticos.",
    privacidade: true,
    limite_participantes: 500,
    tipo: "leitura",
    frequencia: "mensal",
    leitura_atual: null,
    generos: [
      { id: 1, nome: "fantasy" },
      { id: 2, nome: "adventure" },
    ],
    cidade_nome: "Rio de Janeiro",
    estado_sigla: "RJ",
    total_participantes: 1240,
  },
  {
    id: "2",
    nome: "Clube Mistério Urbano",
    descricao:
      "Suspense, thrillers e histórias que te prendem até a última página.",
    privacidade: false,
    limite_participantes: 300,
    tipo: "leitura",
    frequencia: "quinzenal",
    leitura_atual: null,
    generos: [
      { id: 3, nome: "mystery" },
      { id: 4, nome: "thriller" },
    ],
    cidade_nome: "São Paulo",
    estado_sigla: "SP",
    total_participantes: 890,
  },
  {
    id: "3",
    nome: "Clube Romance Contemporâneo",
    descricao: "Histórias de amor modernas, reais e cheias de emoção.",
    privacidade: false,
    limite_participantes: null,
    tipo: "leitura",
    frequencia: "mensal",
    leitura_atual: null,
    generos: [{ id: 5, nome: "romance" }],
    cidade_nome: "Belo Horizonte",
    estado_sigla: "MG",
    total_participantes: 1520,
  },
];

export const allClubs: Club[] = [
  ...recommendedClubs,

  {
    id: "4",
    nome: "Clube Sci-Fi Orbit",
    descricao: "Exploração espacial, tecnologia e futuros possíveis.",
    privacidade: true,
    limite_participantes: 800,
    tipo: "leitura",
    frequencia: "mensal",
    leitura_atual: null,
    generos: [{ id: 6, nome: "sci-fi" }],
    cidade_nome: "Curitiba",
    estado_sigla: "PR",
    total_participantes: 980,
  },
  {
    id: "5",
    nome: "Clube Poesia Viva",
    descricao: "Poemas clássicos e contemporâneos que tocam a alma.",
    privacidade: false,
    limite_participantes: 200,
    tipo: "leitura",
    frequencia: "semanal",
    leitura_atual: null,
    generos: [{ id: 7, nome: "poetry" }],
    cidade_nome: "Porto Alegre",
    estado_sigla: "RS",
    total_participantes: 430,
  },
  {
    id: "6",
    nome: "Clube Clássicos Brasileiros",
    descricao: "Literatura brasileira em sua forma mais rica e histórica.",
    privacidade: false,
    limite_participantes: null,
    tipo: "leitura",
    frequencia: "mensal",
    leitura_atual: null,
    generos: [
      { id: 8, nome: "classic" },
      { id: 9, nome: "literature" },
    ],
    cidade_nome: "Salvador",
    estado_sigla: "BA",
    total_participantes: 670,
  },
  {
    id: "7",
    nome: "Clube Horror & Sombras",
    descricao: "Histórias sombrias, terror psicológico e suspense intenso.",
    privacidade: true,
    limite_participantes: 400,
    tipo: "leitura",
    frequencia: "mensal",
    leitura_atual: null,
    generos: [{ id: 10, nome: "horror" }],
    cidade_nome: "Recife",
    estado_sigla: "PE",
    total_participantes: 760,
  },
];
